src/Controllers/CMSPageHistoryViewerController.php
Fixes #3 
The issue is that there was no ID field present, so LeftAndMain.Preview.js would render the edit panel again:
https://github.com/silverstripe/silverstripe-admin/blob/4166209a16069151260c90285f5a347ea2ce8276/client/src/legacy/LeftAndMain.Preview.js#L526-L530
=> FIX Ensure CMS history tab has a hidden ID field to prevent switching back to Content tab

.travis.yml, tests/Behat/Context/FeatureContext.php, tests/Behat/features/list-view.feature, tests/Behat/features/view-a-version.feature
Additions were made to the FeatureContext to allow to assert text being contained within specific columns within specific versions. The intention is that this allows modularity for further tests.
Note that the following workaround `And I go to "/admin/pages/history/show/1"` was used to navigate to the History, rather than clicking the History tab. This is because of the popup notice that hides (and prevents from clicking) the History tab - see: https://github.com/silverstripe/silverstripe-cms/issues/2128 Unfortunately, dismissing the pop up and waiting for it to fade away has been unreliable.
=> Add Behat feature and (context) to view a list of versions in History Viewer

_config/cms.yml, behat.yml, composer.json, phpcs.xml.dist, src/Controllers/HistoryControllerFactory.php, src/Controllers/HistoryViewerController.php, src/Forms/DataObjectVersionFormFactory.php, tests/Behat/Stub/EnableHistoryViewerExtension.php, tests/Behat/config/enable-historyviewer.yml, tests/Behat/features/list-view.feature, tests/Behat/features/view-a-version.feature, tests/Controllers/CMSPageHistoryViewerControllerTest.php
Resolves  https://github.com/silverstripe/silverstripe-versioned-admin/issues/15
This allows the data record to provide context to whether the history viewer should be activated or not. Example activation point: https://github.com/dnadesign/silverstripe-elemental/pull/231
=> NEW Allow history viewer to be activated by modules rather than always on

src/Controllers/HistoryControllerFactory.php
In #13 this change had originally made a behat test fail, perhaps the test has been updated so workaround that, but this is the fix to ensure that the page can be loaded when the reading mode is Stage.Live
=> FIX Ensure history controller factory reads current page from Draft stage

src/Controllers/HistoryControllerFactory.php
Particuarly in unit testing, there may not always be a request available at this point. This patch checks first and returns the default history controller if there isn't one available yet.
Example:
```
1) Symbiote\QueuedJobs\Tests\QueuedJobsAdminTest::testConstructorParamsShouldBeATextarea
Missing argument 1 for SilverStripe\Control\HTTPRequest::__construct()
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverstripe/framework/src/Control/HTTPRequest.php:157
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverstripe/framework/src/Core/Injector/InjectionCreator.php:26
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverstripe/framework/src/Core/Injector/Injector.php:585
/home/travis/build/silverstripe/cwp-recipe-kitchen-sink/vendor/silverst …
```
=> FIX Return default history controller when no request is available in injector

src/Controllers/CMSPageHistoryViewerController.php, tests/Behat/features/revert-to-a-version.feature
We use the HistoryControllerFactory to determine this instead.
This meant that in practice the factory response was being ignored in favour of this controller anyway. Testing with this fix in place resolves the issue.
Fixes https://github.com/silverstripe/cwp/issues/110
=> FIX Lower URL priority so controller is not auto loaded over CMSPageHistoryController

.travis.yml, composer.json
Parent issue silverstripeltd/open-sourcerers#31
=> Install 5.x-dev recipe when testing master.

src/Controllers/HistoryControllerFactory.php, tests/Controllers/HistoryControllerFactoryTest.php, tests/Controllers/HistoryControllerFactoryTest.yml, tests/Controllers/HistoryControllerFactoryTest/HistoryControllerFactoryExtension.php
I had trouble reproducing this using the steps that @Cheddam provided but I managed to reproduce it consistently with a test (that I've added to this commit). Yay for TDD!
Resolves #51
=> FIX Use get_one_by_stage when fetching SiteTree for a specific stage

src/Controllers/HistoryControllerFactory.php
This fixes a bug surfacing in reports in elemental when using Postgres
where a FQCN is passed as the ID instead (from LeftAndMain::getCombinedClientConfig)
=> FIX Check ID is numeric before using it

src/ArchiveAdmin.php, src/Extensions/FileArchiveExtension.php
This fixes a couple of small issues in archive admin:
1. `ArchiveViewProvider` had an `isArchiveFieldEnabled` function for determining if a given archive view should be presented as a tab in 'Archives' – currently uses for 'Files' archive tab to only show if the setting for assets to be retained when deleted is set. This function wasn't actually leveraged by ArchiveAdmin so has been added.
2. There was an issue with the files gridfield showing the count for records that weren't displayed due to canView permissions, so we do that check sooner so the paginator and page count report the correct count.
=> Archive add missing tab logic, fix file list

tests/ArchiveAdminTest/ViewProviderVersionedObject.php
**Versions** 
Framework: 4.3.0
versioned-admin: 1.1
I can replicate this only in CircleCI. Not sure why it's not breaking in my local.
Please back fix this into v1.1 as well. 
**Circle CI error**
Fatal error: Maximum function nesting level of '256' reached, aborting! in /var/www/html/vendor/silverstripe/framework/src/ORM/Connect/MySQLiConnector.php on line 49
**Actual PHP Error**
Fatal error: Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query:
CREATE  TABLE "SilverStripe_VersionedAdmin_Tests_ArchiveAdminTest_ViewProviderVersionedObject" (
"ID" int(11) not null auto_increment,
"ClassName" enum('SilverStripe\\VersionedAdmin\\Tests\\ArchiveAdminTest\\ViewProviderVersionedObject','SilverStripe\\VersionedAdmin\\Tests\\ArchiveAdminTest\\ViewProviderChildObject') character …
=> Add missing implement TestOnly in ViewProviderVersionedObject - unit tests failing.

src/Controllers/HistoryViewerController.php, tests/Controllers/HistoryViewerControllerTest.php
This is a "NEW" but is actually data integrity fix. Currently fetching a record by version number doesn't necessarily give you accurate information for related objects in history. Fetching the dataobject using archive mode set to a date is more accurate.
=> NEW Allow fetching history from schema by date rather than version

.travis.yml, src/ArchiveAdmin.php
See issue #102 ArchiveAdmin appears to require CMS JS/CSS but apparently doesn't need them.
I have done this on branch 1.1 as this appears to be the earliest point `ArchiveAdmin` exists.
=> Remove CMS requirement from ArchiveAdmin

.travis.yml, _config/cms.yml, src/ArchiveAdmin.php, src/Extensions/CMSMainExtension.php, src/Forms/HistoryViewerField.php, tests/Forms/HistoryViewerFieldTest.php
The extension that provided this config was only applying to CMSMain which would not help history viewers that weren't loading outside of a CMS page context (eg. ModelAdmin). This PR makes the HistoryViewer JS apply more globally using a method similar to other modules that provide fields.
=> FIX Use a more reliable method of including client bundles

composer.json, phpcs.xml.dist, src/ArchiveAdmin.php, src/Controllers/HistoryViewerController.php, tests/Controllers/HistoryControllerFactoryTest.php
Still has some exclusions which would require core API changes, this is updating Travis to use PSR-12 (unstable at this point) and running automated linting
Issue: https://github.com/silverstripe/silverstripe-framework/issues/7991
=> Update phpcs to use PSR-12 (with exclusions) and run automated linting

lang/en.yml, src/ArchiveAdmin.php
Fixes https://github.com/silverstripe/silverstripe-versioned/issues/207
You can get the Files tab to easily show by return true from `FileArchiveExtension::isArchiveFieldEnabled()`
(most installations will probably have this set to false and won't show the Files tab)
Default tab is selected
Before
After
=> FIX Reorder model tabs

src/Extensions/BlockArchiveExtension.php
Fix for https://github.com/silverstripe/silverstripe-versioned-admin/issues/118
PR was originally https://github.com/silverstripe/silverstripe-versioned-admin/pull/141, though that was based from and targeting `master` instead of `1.6` - seemed easier to just redo and put down Co-authors in the commit message
Have replicated issue and tested locally that the solution in the original PR works correctly
Co-authored-by: Kong Jin Jie <jinjie@swiftdev.sg>
Co-authored-by: Robbie Averill <robbie@averill.co.nz>
=> FIX Prevent exception when parent does not have breadcrumbs

tests/Controllers/HistoryControllerFactoryTest.php, tests/Controllers/HistoryControllerFactoryTest/HistoryControllerFactoryExtension.php
Fixes a super minor issue
> Deprecation Notice: Class SilverStripe\VersionedAdmin\Tests\Controller\HistoryControllerFactory\HistoryControllerFactoryExtension located in ./vendor/silverstripe/versioned-admin/tests/Controllers/HistoryControllerFactoryTest/HistoryControllerFactoryExtension.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///opt/bitnami/php/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
=> BUG Fix issue with composer warning about PSR-4 paths

lang/en.yml, src/Forms/DiffField.php, tests/Forms/DiffFieldTest.php
In particular, this stops TreeMultiselectField values from breaking the comparison UI.
A more in-depth fix would introduce support for diffing these values, but there are multiple issues to address before this can be implemented, such as DiffField not honoring custom setValue methods on FormField sub-classes.
Fixes silverstripe/silverstripe-framework#9843.
Fixes silverstripe/silverstripe-framework#9839.
=> FIX Avoid attempting to diff object-based field values

_config/cms.yml, _config/requirements.yml
If installed in a framework-only installation, the missing JS and CSS causes the interface to break. This fix ensures that the dependencies are always loaded.
Fixes #183
=> BUG don't disable bundle.js / bundle.css with no-cms install

README.md
Resolves https://github.com/silverstripe/silverstripe-versioned-admin/issues/121
I figure if someone wants to see screenshots and features included in the module the CMS User help would be a good source of truth. I've noted there's not really a consistent way of doing this for core modules but thought I'd raise this incase it's useful.
=> DOCS include userhelp link in versioned-admin readme
